spring.application.name=LogiTrack

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3307/LogiTrack}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Samira12}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true
spring.flyway.locations=classpath:db/migration

app.jwt.secret=${JWT_SECRET:MaCleSecreteSuperLongueEtSecurisee1234567890!}
app.jwt.expiration=${JWT_EXPIRATION:86400000}

spring.data.redis.host=${SPRING_DATA_REDIS_HOST:localhost}
spring.data.redis.port=${SPRING_DATA_REDIS_PORT:6379}

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=logitrack
management.prometheus.metrics.export.enabled=true

notification.service.url=http://localhost:8081
